# Generated by Django 5.0.4 on 2024-04-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, verbose_name="Category")),
            ],
        ),
        migrations.CreateModel(
            name="ContractModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Contract value")),
                ("information", models.TextField(verbose_name="Contract information")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Date of creation")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date of update")),
                (
                    "cathegory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="contracts.category",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
    ]
